name: task_master_prototype
description: A new Flutter project.

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.7+3
  speech_to_text: ^7.0.0
  flutter_sound: ^9.3.8
  provider: ^6.0.0
  intl: ^0.17.0
  table_calendar: ^3.0.0
  flutter_local_notifications: ^18.0.1
  firebase_core: ^2.16.0
  firebase_analytics: ^10.10.7
  cloud_firestore: ^4.7.5
  crypto: ^3.0.0
  confetti: ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/badDiamond.png
    - assets/images/badFist.png
    - assets/images/badStar.png
    - assets/images/dark.png
    - assets/images/notif.png
    - assets/images/pic1.png
    - assets/images/pic2.png
    - assets/images/pic3.png
    - assets/images/pic4.png
    - assets/images/token.png
