// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFF5QR8kQjKppxg_11LSY-DXAOeI3JqM',
    appId: '1:201460636241:web:910fb7c75c999080e2b670',
    messagingSenderId: '201460636241',
    projectId: 'task-master-prototype',
    authDomain: 'task-master-prototype.firebaseapp.com',
    storageBucket: 'task-master-prototype.firebasestorage.app',
    measurementId: 'G-YJSQQFPJQ7',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGV6nsed2f9A-AX1W5ah3bOao_tEpSWg',
    appId: '1:201460636241:android:e47dac58dbe07468e2b670',
    messagingSenderId: '201460636241',
    projectId: 'task-master-prototype',
    storageBucket: 'task-master-prototype.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFF5QR8kQjKppxg_11LSY-DXAOeI3JqM',
    appId: '1:201460636241:web:eea12d863d38c9cbe2b670',
    messagingSenderId: '201460636241',
    projectId: 'task-master-prototype',
    authDomain: 'task-master-prototype.firebaseapp.com',
    storageBucket: 'task-master-prototype.firebasestorage.app',
    measurementId: 'G-DSZWY8MPJP',
  );
}
